import { CheckBox } from "@/components/CustomComponents/dynamic-checkbox";

export const COMPONENTS = [
    {
        id: "dynamic-checkbox",
        name: "Dynamic Checkbox",
        tags: ["checkbox", "form", "input", "accessibility"],
        Category: "Form",
        shortDescription: "A highly customizable and accessible checkbox component designed for modern web applications. It supports dynamic state changes, including indeterminate states, and provides a smooth user experience with motion-enhanced transitions.",
        description: "An accessible, motion-enhanced checkbox built for modern UI libraries. It animates state changes (unchecked → indeterminate → checked) using subtle scale, opacity and stroke-dash transitions for instant affordance without distraction. The check glyph (or custom icon) is drawn with a springy path reveal while the container background and border smoothly morph to their active tokens. Supports controlled and uncontrolled usage, indeterminate tri-state, disabled, read-only, invalid, and loading states. Keyboard interactions (Space / Enter) mirror native behavior; focus ring is token-driven and respects prefers-reduced-motion (automatically swaps to non-animated state changes). Theme-ready via design tokens (size, radius, border width, color roles) with built‑in size variants (sm, md, lg) and density scaling. Dark mode and high-contrast safe (minimum contrast enforced). RTL-compatible (no directional assumptions). Emits granular callbacks (onChange, onIndeterminateChange) and forwards refs for form libraries. Motion layer is isolated so animations can be disabled per instance. Minimal DOM footprint, no layout shift, and tree-shakeable. Designed for composability: label slot, description / hint / error regions, optional tooltip trigger, and icon override. Ideal for dynamic lists and preference panels needing responsive visual feedback while preserving performance and accessibility. Provides ARIA-compliant semantics with proper role=checkbox and aria-checked tri-state handling, auto-generates accessible name from associated label, and exposes optional aria-describedby linkage for hint or error text. Fully SSR-safe with hydration-stable markup; no layout thrash (avoids measuring) and 60fps animations under typical load. Tested across modern evergreen browsers and gracefully degrades in legacy ones (falls back to instant state changes). Integrates cleanly with React Hook Form, Formik, and uncontrolled HTML forms. Offers deterministic test IDs and stable DOM structure for reliable unit and E2E testing. Includes optional reduced-interaction mode for low-power or battery saver contexts and supports color-blind friendly contrast tokens. Code-splittable and side-effect free for tree shaking. Supports icon override, custom state render, analytics hooks, and intent-based styling (success / warning / error) via data-* attributes.",
        Code: <CheckBox />
    }
];